name: Generate CN IP List v3

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install geoip2 maxminddb requests

      - name: Run generator
        run: python generate_address_list_v3.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add CN_v3 CN_v3.rsc
          git commit -m "Auto update CN IP List v3 at $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
